### ISSUE TITLE
How to use command line tool

### ISSUE THREAD

**Issue by mysablehats** [biomedia-mira/dixonfix#1]
I was wondering what is the correct usage of this tool.

I tried multiple different file inputs but I keep getting this error:
     
     $  ../dixonfix -f fat.nii -w water.nii
                DIXON-FIX
    ---------------------------------

     + loading and resampling images...WARNING: In /home/frekle/github/dixonfix/3rdParty/InsightToolkit-5.0.0/Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx, line 57
     GDCMSeriesFileNames (0x55792651de80): You need to specify a directory where the DICOM files are located
    (...)

**Comment by bglocker** [comment]
Please see this example for how to run dixonfix: https://www.dropbox.com/s/khxlttf38t2o481/dixonfix-demo.zip?dl=0

Note, that you would need to first train your own regression forest on a set of 'clean' Dixon scans with water, fat, in- and out-of-phase images. The example above does only contain a few images to illustrate how to run it, but in practice one would require a larger set of training images.

**Comment by jhirschAtMEVIS** [comment]
Thanks for the comments, help a lot!
I'm wondering how to use the Windows binaries in Linux ... Would it be possible to add the Linux binaries "oak2*" to the demo directory? (dixonfix is available from the git compilation.)

**Comment by bglocker** [comment]
The oak2 library is available here [https://github.com/biomedia-mira/oak2](https://github.com/biomedia-mira/oak2) and should compile under Linux. I'm afraid I don't have the binaries readily available to add to the demo.
